language: php

php:
    - 5.3

env:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1
#    - php: 5.6
#      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=2
#    - php: 5.6
#      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=3
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=master
  allow_failures:
    - env: DB=SQLITE CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: ./shop/tests/travis/run_build.sh

after_script:
  - if [ "$COVERAGE" > 0 ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  - cd shop
  - wget https://scrutinizer-ci.com/ocular.phar
  - ../vendor/bin/ocular code-coverage:upload -v --format=php-clover build/logs/coverage.xml
  - CODECLIMATE_REPO_TOKEN=1bda7e981e23a213cae7976d3cf7e93054cd28fca1547e7813eb4ef568cdea29 ../vendor/bin/test-reporter
  - fi

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
